import React, { useState } from 'react';
import { ArrowRight, ArrowUpRight, Compass, MapPin, Mountain, Menu, Sparkles, X, Waves, Trees, Camera, CalendarDays } from 'lucide-react';

type Page = 'home' | 'solutions' | 'process' | 'pricing' | 'about' | 'contact';
const navItems: { label: string; href: string; page: Page }[] = [
  { label: 'Home', href: '/', page: 'home' },
  { label: 'Destinations', href: '/solutions', page: 'solutions' },
  { label: 'Travel tips', href: '/process', page: 'process' },
  { label: 'Plan a visit', href: '/pricing', page: 'pricing' },
  { label: 'About', href: '/about', page: 'about' },
];
const places = [
  { name: 'Hunza Valley', area: 'Hunza District', text: 'Mountain views, welcoming villages, orchards and historic forts.', image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=85', tag: 'Mountain escape' },
  { name: 'Attabad Lake', area: 'Upper Hunza', text: 'Brilliant turquoise water surrounded by dramatic rocky peaks.', image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85', tag: 'Lakeside views' },
  { name: 'Fairy Meadows', area: 'Diamer', text: 'A legendary alpine meadow with unforgettable views of Nanga Parbat.', image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=85', tag: 'For adventurers' },
  { name: 'Skardu', area: 'Baltistan', text: 'Gateway to high peaks, cold deserts, lakes and Balti heritage.', image: 'https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=1200&q=85', tag: 'Explore Baltistan' },
];
function ButtonLink({ href, children, secondary = false }: { href: string; children: React.ReactNode; secondary?: boolean }) {
  return <a href={href} className={`inline-flex items-center justify-center gap-2 rounded-full px-5 py-3 text-sm font-semibold transition ${secondary ? 'border border-white/20 bg-white/10 text-white hover:bg-white/15' : 'bg-amber-300 text-slate-950 hover:bg-amber-200'}`}>{children}</a>;
}
function Header({ page }: { page: Page }) {
  const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-50 border-b border-white/10 bg-[#07131b]/90 backdrop-blur-xl">
    <div className="mx-auto flex h-[74px] max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8">
      <a href="/" className="flex items-center gap-3" aria-label="Gilgit Portal home">
        <span className="grid h-10 w-10 place-items-center rounded-2xl bg-amber-300 text-slate-950"><Mountain size={23}/></span>
        <span><span className="block text-lg font-extrabold tracking-tight text-white">Gilgit<span className="text-amber-300"> Portal</span></span><span className="hidden text-[9px] font-bold uppercase tracking-[.2em] text-slate-400 sm:block">Discover the extraordinary north</span></span>
      </a>
      <nav className="hidden items-center gap-1 lg:flex" aria-label="Main navigation">{navItems.map(n=><a key={n.page} href={n.href} className={`rounded-full px-3.5 py-2.5 text-sm font-medium transition ${page===n.page?'bg-white/10 text-amber-200':'text-slate-300 hover:bg-white/10 hover:text-white'}`}>{n.label}</a>)}</nav>
      <div className="hidden lg:block"><ButtonLink href="/contact">Start exploring <ArrowUpRight size={16}/></ButtonLink></div>
      <button className="grid h-10 w-10 place-items-center rounded-full border border-white/15 text-white lg:hidden" aria-label={open?'Close menu':'Open menu'} onClick={()=>setOpen(!open)}>{open?<X size={20}/>:<Menu size={20}/>}</button>
    </div>
    {open&&<nav className="border-t border-white/10 bg-[#07131b] px-4 py-3 lg:hidden">{navItems.map(n=><a key={n.page} onClick={()=>setOpen(false)} href={n.href} className="block rounded-xl px-4 py-3 text-sm text-slate-200 hover:bg-white/10">{n.label}</a>)}<a href="/contact" className="mt-2 block rounded-xl bg-amber-300 px-4 py-3 text-center text-sm font-bold text-slate-950">Start exploring</a></nav>}
  </header>;
}
function Eyebrow({ children }: { children: React.ReactNode }) { return <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-amber-200/30 bg-amber-200/10 px-3.5 py-2 text-[11px] font-bold uppercase tracking-[.16em] text-amber-100"><span className="h-1.5 w-1.5 rounded-full bg-amber-300"/>{children}</div>; }
function PageHero({ eyebrow, title, text }: { eyebrow:string; title:string; text:string }) {
  return <section className="border-b border-white/10 px-4 py-16 sm:px-6 sm:py-20 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><Eyebrow>{eyebrow}</Eyebrow><h1 className="max-w-4xl text-4xl font-extrabold leading-tight tracking-[-.04em] text-white sm:text-5xl lg:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-300 sm:text-lg">{text}</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/contact">Plan your trip <ArrowUpRight size={16}/></ButtonLink><ButtonLink href="/" secondary>Back to home <ArrowRight size={16}/></ButtonLink></div></div></section>;
}
function PlaceCards() { return <div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">{places.map((p,i)=><article key={p.name} className="group overflow-hidden rounded-[26px] border border-white/10 bg-white/[0.04] transition hover:-translate-y-1 hover:border-amber-200/40"><div className="relative h-56 overflow-hidden"><img src={p.image} alt={p.name} loading="lazy" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><span className="absolute left-4 top-4 rounded-full bg-[#07131b]/80 px-3 py-1.5 text-[11px] font-semibold text-amber-100 backdrop-blur">{p.tag}</span></div><div className="p-5"><div className="flex items-center gap-1.5 text-xs text-amber-200"><MapPin size={13}/>{p.area}</div><h3 className="mt-2 text-xl font-bold text-white">{p.name}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{p.text}</p><a href="/contact" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-amber-200">Explore destination <ArrowRight size={15}/></a></div></article>)}</div>; }
function HomePage() {
  return <>
    <section className="relative isolate flex min-h-[590px] items-center overflow-hidden px-4 py-20 sm:px-6 lg:min-h-[680px] lg:px-8">
      <img src="https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=2200&q=90" alt="Snow-covered mountain peaks beneath a starry sky" className="absolute inset-0 -z-20 h-full w-full object-cover object-center"/>
      <div className="absolute inset-0 -z-10 bg-gradient-to-r from-[#06121b]/95 via-[#06121b]/70 to-[#06121b]/20"/><div className="absolute inset-0 -z-10 bg-gradient-to-t from-[#07131b] via-transparent to-[#07131b]/20"/>
      <div className="mx-auto w-full max-w-7xl"><div className="max-w-3xl"><Eyebrow><Compass size={13}/> Gilgit-Baltistan · Pakistan</Eyebrow><h1 className="text-5xl font-extrabold leading-[1.04] tracking-[-.05em] text-white sm:text-6xl lg:text-7xl">Find your way to the <span className="text-amber-300">majestic north.</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-200 sm:text-lg">Discover soaring peaks, turquoise lakes, ancient forts and the vibrant cultures of Gilgit-Baltistan. Your journey into the mountains starts here.</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/solutions">Explore destinations <ArrowRight size={17}/></ButtonLink><ButtonLink href="/contact" secondary>Plan your visit <MapPin size={16}/></ButtonLink></div><div className="mt-12 flex flex-wrap gap-x-7 gap-y-3 text-sm text-slate-200"><span className="flex items-center gap-2"><Mountain size={17} className="text-amber-300"/> Himalayan landscapes</span><span className="flex items-center gap-2"><Waves size={17} className="text-amber-300"/> Alpine lakes</span><span className="flex items-center gap-2"><Trees size={17} className="text-amber-300"/> Living heritage</span></div></div></div>
    </section>
    <section className="px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="mb-9 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Eyebrow>Places worth the journey</Eyebrow><h2 className="text-3xl font-extrabold tracking-tight text-white sm:text-4xl">Discover the north</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base">From peaceful valleys to legendary mountain trails, every destination has a story.</p></div><a href="/solutions" className="inline-flex items-center gap-2 text-sm font-semibold text-amber-200">All destinations <ArrowRight size={16}/></a></div><PlaceCards/></div></section>
    <section className="border-y border-white/10 bg-[#0b1b25] px-4 py-16 sm:px-6 lg:px-8 lg:py-20"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><Eyebrow>More than a view</Eyebrow><h2 className="text-3xl font-extrabold tracking-tight text-white sm:text-4xl">A land of extraordinary culture and hospitality.</h2><p className="mt-5 text-sm leading-7 text-slate-300 sm:text-base">Meet local communities, discover regional food and crafts, explore historic forts, and travel with respect for the landscapes and people who make this region unique.</p><div className="mt-7"><ButtonLink href="/about">Get to know the region <ArrowRight size={16}/></ButtonLink></div></div><div className="grid grid-cols-2 gap-3"><div className="overflow-hidden rounded-3xl"><img className="h-52 w-full object-cover sm:h-64" loading="lazy" src="https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=900&q=80" alt="Traditional architecture and mountain town"/></div><div className="mt-8 overflow-hidden rounded-3xl"><img className="h-52 w-full object-cover sm:h-64" loading="lazy" src="https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=900&q=80" alt="Peaceful alpine lake and mountains"/></div></div></div></section>
    <section className="px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-4 md:grid-cols-3">{[{icon:Camera,title:'Explore responsibly',text:'Respect local customs, keep trails clean and leave nature as you found it.'},{icon:CalendarDays,title:'Plan ahead',text:'Check seasonal conditions, road updates and local guidance before travelling.'},{icon:MapPin,title:'Go with local knowledge',text:'Ask local guides and communities for advice on routes, culture and safety.'}].map(x=><article key={x.title} className="rounded-3xl border border-white/10 bg-white/[0.035] p-6"><x.icon className="text-amber-200" size={24}/><h3 className="mt-4 text-lg font-bold text-white">{x.title}</h3><p className="mt-2 text-sm leading-6 text-slate-300">{x.text}</p></article>)}</div></section>
    <section className="px-4 pb-20 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-6 rounded-[30px] border border-amber-200/20 bg-gradient-to-br from-amber-200/10 via-[#0d2029] to-[#10212b] p-7 sm:p-10 lg:flex-row lg:items-center lg:justify-between lg:p-14"><div><Eyebrow>Your next adventure</Eyebrow><h2 className="text-3xl font-extrabold text-white sm:text-4xl">The mountains are calling.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base">Start planning a thoughtful trip to Gilgit-Baltistan. Use the portal chatbot for general questions, and verify current travel conditions with local authorities.</p></div><ButtonLink href="/contact">Plan a visit <ArrowUpRight size={16}/></ButtonLink></div></section>
  </>;
}
function DestinationsPage(){return <><PageHero eyebrow="Explore Gilgit-Baltistan" title="Four unforgettable places to begin." text="Use these destination highlights to start planning. Travel times, access and conditions vary by season, so check local updates before departure."/><section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><PlaceCards/></div></section></>;}
function TravelTipsPage(){const tips=[['Choose the season','Summer is a popular time for many valleys and high-altitude routes. Weather can change quickly, especially in the mountains.'],['Check roads and weather','Confirm road status, weather, and any local advisories shortly before departure. Do not rely on old social media posts for live conditions.'],['Pack for changing conditions','Bring layers, sun protection, sturdy footwear and any personal essentials. Higher elevations can be cold even when valleys are warm.'],['Respect local communities','Ask before photographing people, dress respectfully, follow local guidance and support local businesses where possible.']];return <><PageHero eyebrow="Travel tips" title="Travel thoughtfully. Explore safely." text="A little preparation helps make a trip through Gilgit-Baltistan more comfortable and respectful."/><section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-4 md:grid-cols-2">{tips.map(([title,text],i)=><article key={title} className="rounded-3xl border border-white/10 bg-white/[0.035] p-7"><span className="text-sm font-bold text-amber-200">0{i+1}</span><h2 className="mt-3 text-xl font-bold text-white">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-300">{text}</p></article>)}</div></section></>;}
function PlanningPage(){return <><PageHero eyebrow="Plan a visit" title="Build your trip around the experience you want." text="Whether you want quiet lakeside time, cultural exploration or a challenging mountain adventure, begin with your dates, route and comfort level."/><section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-4 md:grid-cols-3">{[{title:'A relaxed escape',text:'Choose accessible viewpoints, valley walks, local food and time to enjoy the scenery.'},{title:'Culture and heritage',text:'Explore historic sites, traditional settlements, local crafts and regional cuisine with respect.'},{title:'An outdoor adventure',text:'Research route difficulty, permits where required, weather windows and qualified local guides.'}].map(x=><article key={x.title} className="rounded-3xl border border-white/10 bg-white/[0.035] p-7"><h2 className="text-xl font-bold text-white">{x.title}</h2><p className="mt-3 text-sm leading-7 text-slate-300">{x.text}</p></article>)}</div><p className="mx-auto mt-6 max-w-7xl text-xs leading-6 text-slate-400">This portal provides general inspiration, not live road, weather, emergency or official travel-status updates. Verify current details with relevant local authorities.</p></section></>;}
function AboutPage(){return <><PageHero eyebrow="About Gilgit Portal" title="A welcoming guide to the north of Pakistan." text="Gilgit Portal brings destination inspiration, practical travel guidance and appreciation for the region's diverse communities into one clear, accessible place."/><section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-3">{[{icon:Mountain,title:'Nature',text:'Dramatic mountain ranges, glaciers, valleys and high-altitude lakes.'},{icon:Trees,title:'Culture',text:'Distinct local languages, traditions, crafts, food and warm hospitality.'},{icon:Compass,title:'Discovery',text:'Helpful starting points for exploring destinations and preparing for travel.'}].map(x=><article key={x.title} className="rounded-3xl border border-white/10 bg-white/[0.035] p-7"><x.icon size={25} className="text-amber-200"/><h2 className="mt-5 text-xl font-bold text-white">{x.title}</h2><p className="mt-3 text-sm leading-7 text-slate-300">{x.text}</p></article>)}</div></section></>;}
function ContactPage(){return <><PageHero eyebrow="Get in touch" title="Start planning your Gilgit-Baltistan journey." text="Use the portal chatbot for general destination questions, or plan your route with reliable local travel providers and official sources."/><section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-3xl rounded-3xl border border-white/10 bg-white/[0.035] p-7 sm:p-10"><h2 className="text-2xl font-bold text-white">Before you travel</h2><p className="mt-4 text-sm leading-7 text-slate-300">Confirm transport, accommodation, road conditions, weather and any route-specific requirements. For immediate or official information, contact the relevant local authority or a trusted local operator.</p><div className="mt-6 flex flex-wrap gap-3"><ButtonLink href="/solutions">Browse destinations <ArrowRight size={16}/></ButtonLink><ButtonLink href="/" secondary>Return home</ButtonLink></div></div></section></>;}
function Footer(){return <footer className="border-t border-white/10 bg-[#050e14] px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 sm:flex-row sm:items-center"><a href="/" className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-amber-300 text-slate-950"><Mountain size={19}/></span><span className="font-extrabold text-white">Gilgit <span className="text-amber-300">Portal</span></span></a><p className="max-w-xl text-xs leading-6 text-slate-400">Destination inspiration and general travel guidance for Gilgit-Baltistan, Pakistan. Check official sources for current conditions and announcements.</p><span className="text-xs text-slate-500">© {new Date().getFullYear()} Gilgit Portal</span></div></footer>;}
export default function OrkenSite(){const path=window.location.pathname.replace(/\/+$/,'')||'/';const page:Page=path==='/solutions'?'solutions':path==='/process'?'process':path==='/pricing'?'pricing':path==='/about'?'about':path==='/contact'?'contact':'home';const titles:Record<Page,string>={home:'Gilgit Portal | Discover Gilgit-Baltistan',solutions:'Destinations | Gilgit Portal',process:'Travel Tips | Gilgit Portal',pricing:'Plan a Visit | Gilgit Portal',about:'About Gilgit Portal',contact:'Plan Your Visit | Gilgit Portal'};const descriptions:Record<Page,string>={home:'Discover the majestic mountains, valleys, lakes, culture and destinations of Gilgit-Baltistan, Pakistan.',solutions:'Explore Hunza Valley, Attabad Lake, Fairy Meadows, Skardu and more places in Gilgit-Baltistan.',process:'Practical, responsible travel tips for exploring Gilgit-Baltistan.',pricing:'Start planning a trip to Gilgit-Baltistan with destination ideas and useful travel preparation.',about:'Learn about Gilgit Portal, a welcoming guide to the nature and culture of northern Pakistan.',contact:'Prepare for your Gilgit-Baltistan visit with useful planning guidance.'};document.title=titles[page];const meta=document.querySelector('meta[name="description"]');if(meta)meta.setAttribute('content',descriptions[page]);return <div className="min-h-screen bg-[#07131b] text-white selection:bg-amber-300 selection:text-slate-950"><Header page={page}/><main>{page==='home'?<HomePage/>:page==='solutions'?<DestinationsPage/>:page==='process'?<TravelTipsPage/>:page==='pricing'?<PlanningPage/>:page==='about'?<AboutPage/>:<ContactPage/>}</main><Footer/></div>;}
