import React, { useState } from 'react';
import {
  ArrowDownRight, ArrowRight, ArrowUpRight, Bot, BrainCircuit, Check,
  ChevronDown, CirclePlay, Code2, Cpu, Database, Gauge, Headphones,
  Layers3, Menu, MessageSquare, Network, PhoneCall, Radio, ShieldCheck,
  Sparkles, Workflow, X, Zap,
} from 'lucide-react';

type Page = 'home' | 'agents' | 'solutions' | 'process' | 'pricing' | 'about' | 'contact';

const navItems: { label: string; href: string; page: Page }[] = [
  { label: 'Home', href: '/', page: 'home' },
  { label: 'AI Agents', href: '/ai-agents', page: 'agents' },
  { label: 'Solutions', href: '/solutions', page: 'solutions' },
  { label: 'Our Process', href: '/process', page: 'process' },
  { label: 'Pricing', href: '/pricing', page: 'pricing' },
  { label: 'About', href: '/about', page: 'about' },
];

const agents = [
  { icon: PhoneCall, title: 'Voice AI Agents', text: 'Natural inbound and outbound conversations that qualify leads, answer questions, and log every call.' },
  { icon: Headphones, title: 'Customer Support', text: 'Resolve repeat questions around the clock, grounded in your documentation and support history.' },
  { icon: Radio, title: 'Sales SDR Agents', text: 'Research prospects, personalize outreach, follow up, and keep your CRM up to date.' },
  { icon: BrainCircuit, title: 'Custom AI Copilots', text: 'Private assistants that help your team find answers and work with your business knowledge.' },
  { icon: Database, title: 'RAG & Knowledge AI', text: 'Search internal documents with grounded answers, source references, and useful context.' },
  { icon: Workflow, title: 'Workflow Automation', text: 'Connect tools and automate handoffs across sales, operations, reporting, and support.' },
];

const process = [
  { n: '01', title: 'Discover', text: 'We map your workflow, current tools, constraints, and the KPI that matters.' },
  { n: '02', title: 'Design & build', text: 'We choose the right model, connect your systems, and build the agent around real tasks.' },
  { n: '03', title: 'Test in shadow mode', text: 'We evaluate outputs against representative cases, monitor edge cases, and tune guardrails.' },
  { n: '04', title: 'Launch & improve', text: 'Roll out with monitoring, usage visibility, and a plan for continuous improvement.' },
];

const tech = ['Claude', 'GPT-4o', 'Llama', 'n8n', 'Make', 'Pinecone', 'Vapi', 'Langfuse', 'HubSpot', 'Slack', 'Zendesk', 'Supabase'];

function ButtonLink({ href, children, secondary = false }: { href: string; children: React.ReactNode; secondary?: boolean }) {
  return <a href={href} className={`inline-flex items-center justify-center gap-2 rounded-full px-5 py-3 text-sm font-semibold transition duration-200 ${secondary ? 'border border-white/15 bg-white/[0.04] text-white hover:bg-white/10' : 'bg-lime-300 text-slate-950 hover:bg-lime-200'}`}>{children}</a>;
}

function Header({ page }: { page: Page }) {
  const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-50 border-b border-white/[0.08] bg-[#080b12]/90 backdrop-blur-xl">
    <div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between gap-4 px-4 sm:px-6 lg:px-8">
      <a href="/" className="flex items-center gap-2.5" aria-label="Orken AI home">
        <span className="grid h-10 w-10 place-items-center rounded-xl bg-lime-300 text-slate-950"><Sparkles size={22} strokeWidth={2.5}/></span>
        <span><span className="block text-lg font-extrabold tracking-tight text-white">orken<span className="text-lime-300">.ai</span></span><span className="hidden text-[9px] font-bold uppercase tracking-[.22em] text-slate-500 sm:block">AI systems that do the work</span></span>
      </a>
      <nav className="hidden items-center gap-1 lg:flex" aria-label="Main navigation">
        {navItems.map(item => <a key={item.page} href={item.href} className={`rounded-full px-3.5 py-2.5 text-sm font-medium transition ${page === item.page ? 'bg-white/10 text-white' : 'text-slate-400 hover:bg-white/[0.06] hover:text-white'}`}>{item.label}</a>)}
      </nav>
      <div className="hidden lg:block"><ButtonLink href="/contact">Book a free call <ArrowUpRight size={16}/></ButtonLink></div>
      <button className="grid h-10 w-10 place-items-center rounded-full border border-white/10 text-white lg:hidden" aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? <X size={20}/> : <Menu size={20}/>}</button>
    </div>
    {open && <nav className="border-t border-white/10 bg-[#080b12] px-4 py-3 lg:hidden">{navItems.map(item => <a onClick={() => setOpen(false)} key={item.page} href={item.href} className={`block rounded-xl px-4 py-3 text-sm ${page === item.page ? 'bg-white/10 text-lime-300' : 'text-slate-300'}`}>{item.label}</a>)}<a href="/contact" className="mt-2 block rounded-xl bg-lime-300 px-4 py-3 text-center text-sm font-bold text-slate-950">Book a free call <ArrowUpRight className="ml-1 inline" size={16}/></a></nav>}
  </header>;
}

function Eyebrow({ children }: { children: React.ReactNode }) {
  return <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-lime-300/20 bg-lime-300/[0.07] px-3.5 py-2 text-[11px] font-bold uppercase tracking-[.16em] text-lime-200"><span className="h-1.5 w-1.5 rounded-full bg-lime-300"/>{children}</div>;
}

function AgentVisual() {
  return <div className="relative mx-auto w-full max-w-[520px]">
    <div className="absolute -inset-8 rounded-full bg-lime-300/[0.08] blur-3xl"/>
    <div className="relative overflow-hidden rounded-[28px] border border-white/10 bg-[#0d121d] shadow-2xl shadow-black/40">
      <div className="flex items-center justify-between border-b border-white/[0.08] px-5 py-4"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-lime-300"/><span className="text-xs font-semibold text-white">orken-agent / orchestrator</span></div><span className="rounded-full border border-lime-300/20 bg-lime-300/10 px-2.5 py-1 text-[10px] font-bold text-lime-200">SYSTEM ONLINE</span></div>
      <div className="grid grid-cols-2 gap-3 p-4 sm:p-5">
        <div className="col-span-2 rounded-2xl border border-white/[0.08] bg-white/[0.025] p-4"><div className="mb-3 flex items-center justify-between"><span className="text-xs text-slate-400">Workflow overview</span><Workflow size={17} className="text-lime-300"/></div><div className="flex items-center gap-2"><span className="rounded-lg bg-lime-300/10 p-2 text-lime-200"><Zap size={17}/></span><div><div className="text-sm font-semibold text-white">Inbound lead qualification</div><div className="mt-1 text-[11px] text-slate-500">Trigger → Agent → CRM → Follow-up</div></div></div><div className="mt-4 flex h-1.5 gap-1 overflow-hidden rounded-full bg-white/5"><span className="w-[28%] rounded-full bg-lime-300"/><span className="w-[28%] rounded-full bg-lime-300/70"/><span className="w-[28%] rounded-full bg-lime-300/40"/><span className="flex-1 rounded-full bg-white/10"/></div></div>
        {[{icon:BrainCircuit,label:'Reasoning engine',value:'Model + tools'},{icon:Database,label:'Knowledge layer',value:'Context grounded'},{icon:Workflow,label:'Integrations',value:'Connected systems'},{icon:ShieldCheck,label:'Observability',value:'Traces & evals'}].map((x,i)=><div key={x.label} className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-3.5"><x.icon size={18} className={i===3?'text-sky-300':'text-lime-200'}/><div className="mt-3 text-xs font-semibold text-white">{x.label}</div><div className="mt-1 text-[10px] text-slate-500">{x.value}</div></div>)}
        <div className="col-span-2 flex items-center justify-between rounded-2xl border border-white/[0.08] bg-black/20 px-4 py-3"><div className="flex items-center gap-2.5"><span className="grid h-8 w-8 place-items-center rounded-full bg-lime-300 text-slate-950"><Bot size={17}/></span><span className="text-xs text-slate-300">Your AI workforce is ready</span></div><span className="flex items-center gap-1.5 text-[10px] font-semibold text-lime-200"><span className="h-1.5 w-1.5 rounded-full bg-lime-300"/> Monitoring enabled</span></div>
      </div>
    </div>
    <div className="absolute -left-4 top-1/3 hidden rounded-2xl border border-white/10 bg-[#121824] p-3 shadow-xl sm:block"><div className="flex items-center gap-2 text-xs font-semibold text-white"><Check size={15} className="text-lime-300"/> Task completed</div><div className="mt-1 text-[10px] text-slate-500">CRM record updated</div></div>
  </div>;
}

function AgentCards() {
  return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{agents.map((a,i)=><article key={a.title} className="group rounded-3xl border border-white/[0.09] bg-white/[0.025] p-6 transition duration-300 hover:-translate-y-1 hover:border-lime-300/30 hover:bg-white/[0.045]"><div className="mb-6 flex items-center justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl border border-lime-300/15 bg-lime-300/[0.08] text-lime-200"><a.icon size={22}/></span><span className="text-xs font-semibold tracking-widest text-slate-600">0{i+1}</span></div><h3 className="text-lg font-bold text-white">{a.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{a.text}</p><a href="/contact" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-lime-200 transition group-hover:gap-3">Explore solution <ArrowRight size={15}/></a></article>)}</div>;
}

function ProcessSection() {
  return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{process.map((p,i)=><article key={p.n} className="relative rounded-3xl border border-white/10 bg-white/[0.025] p-6"><div className="mb-7 flex items-center justify-between"><span className="text-3xl font-light tracking-tight text-lime-200">{p.n}</span>{i<3&&<ArrowDownRight className="hidden text-slate-700 xl:block" size={22}/>}</div><h3 className="text-lg font-bold text-white">{p.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{p.text}</p></article>)}</div>;
}

function ContactCTA() {
  return <section className="px-4 pb-20 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-7 overflow-hidden rounded-[32px] border border-lime-200/20 bg-gradient-to-br from-lime-300/[0.13] via-[#101a19] to-[#10131d] p-7 sm:p-10 lg:flex-row lg:items-center lg:justify-between lg:p-14"><div className="max-w-2xl"><Eyebrow>Have a workflow in mind?</Eyebrow><h2 className="text-3xl font-extrabold tracking-tight text-white sm:text-4xl">Let’s put your AI to work.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-slate-300 sm:text-base">Tell us what slows your team down. We’ll help you identify the right agent, integrations, and next step.</p></div><div className="flex flex-wrap gap-3"><ButtonLink href="/contact">Discuss your project <ArrowUpRight size={16}/></ButtonLink><ButtonLink href="/ai-agents" secondary>Explore AI agents</ButtonLink></div></div></section>;
}

function HomePage() {
  return <>
    <section className="relative overflow-hidden px-4 pb-20 pt-14 sm:px-6 sm:pt-20 lg:px-8 lg:pb-28 lg:pt-24"><div className="pointer-events-none absolute -right-40 top-0 h-[600px] w-[600px] rounded-full bg-lime-300/[0.055] blur-[100px]"/><div className="pointer-events-none absolute left-1/4 top-1/2 h-72 w-72 rounded-full bg-emerald-400/[0.04] blur-[100px]"/><div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.03fr_.97fr]"><div><Eyebrow>AI automation studio · Built for real work</Eyebrow><h1 className="max-w-3xl text-4xl font-extrabold leading-[1.08] tracking-[-.045em] text-white sm:text-5xl lg:text-6xl xl:text-[68px]">Production AI agents that <span className="text-lime-300">do the work.</span></h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-400 sm:text-lg sm:leading-8">We design, build, and integrate AI agents for support, sales, and operations — connected to the tools your team already uses.</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/contact">Build your AI agent <ArrowUpRight size={17}/></ButtonLink><ButtonLink href="/ai-agents" secondary><CirclePlay size={17}/> Explore what we build</ButtonLink></div><div className="mt-10 flex flex-wrap items-center gap-x-6 gap-y-3 border-t border-white/10 pt-6 text-xs text-slate-500"><span className="flex items-center gap-2"><ShieldCheck size={15} className="text-lime-200"/> Built with guardrails</span><span className="flex items-center gap-2"><Gauge size={15} className="text-lime-200"/> Measured against outcomes</span><span className="flex items-center gap-2"><Layers3 size={15} className="text-lime-200"/> Your stack, connected</span></div></div><AgentVisual/></div></section>
    <section className="border-y border-white/[0.07] bg-white/[0.018] px-4 py-7 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col items-start gap-5 lg:flex-row lg:items-center lg:justify-between"><p className="shrink-0 text-[10px] font-bold uppercase tracking-[.2em] text-slate-500">Works with your existing stack</p><div className="flex flex-wrap gap-2">{tech.map(t=><span key={t} className="rounded-full border border-white/[0.09] px-3.5 py-2 text-xs font-medium text-slate-300">{t}</span>)}</div></div></section>
    <section className="px-4 py-20 sm:px-6 lg:px-8 lg:py-28"><div className="mx-auto max-w-7xl"><div className="mb-10 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><Eyebrow>What we build</Eyebrow><h2 className="max-w-2xl text-3xl font-extrabold tracking-tight text-white sm:text-4xl">A digital workforce for your business.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400 sm:text-base">Purpose-built agents, integrated into your operations — not another disconnected chatbot.</p></div><a href="/ai-agents" className="inline-flex items-center gap-2 text-sm font-semibold text-lime-200">All AI agents <ArrowRight size={16}/></a></div><AgentCards/></div></section>
    <section className="border-y border-white/[0.07] bg-[#0b0f18] px-4 py-20 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="mb-10 max-w-2xl"><Eyebrow>How we work</Eyebrow><h2 className="text-3xl font-extrabold tracking-tight text-white sm:text-4xl">From first workflow to production.</h2><p className="mt-4 text-sm leading-7 text-slate-400 sm:text-base">A practical process designed to get the system working, tested, and observable.</p></div><ProcessSection/></div></section>
    <section className="px-4 py-20 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2 lg:items-center"><div><Eyebrow>Production-minded from day one</Eyebrow><h2 className="text-3xl font-extrabold tracking-tight text-white sm:text-4xl">Useful AI needs more than a clever prompt.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-slate-400 sm:text-base">Reliable agents need clear inputs, the right tools, access to relevant knowledge, and a way to evaluate what happens. We build the complete system around the job to be done.</p><div className="mt-7 space-y-4">{['Defined success metrics and evaluation cases','Integrations with your real tools and data','Monitoring, handoffs, and failure handling','Documentation and a clear path to ownership'].map(x=><div key={x} className="flex items-start gap-3 text-sm text-slate-300"><span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-lime-300/10 text-lime-200"><Check size={13}/></span>{x}</div>)}</div><a href="/process" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-lime-200">See our process <ArrowRight size={16}/></a></div><AgentVisual/></div></section>
    <ContactCTA/>
  </>;
}

function PageHero({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) {
  return <section className="relative overflow-hidden border-b border-white/[0.07] px-4 py-16 sm:px-6 sm:py-20 lg:px-8 lg:py-24"><div className="pointer-events-none absolute right-0 top-0 h-96 w-96 rounded-full bg-lime-300/[0.06] blur-[100px]"/><div className="relative mx-auto max-w-7xl"><Eyebrow>{eyebrow}</Eyebrow><h1 className="max-w-4xl text-4xl font-extrabold leading-tight tracking-[-.04em] text-white sm:text-5xl lg:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-400 sm:text-lg">{text}</p><div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/contact">Talk to our team <ArrowUpRight size={16}/></ButtonLink><ButtonLink href="/" secondary>Back to home <ArrowRight size={16}/></ButtonLink></div></div></section>;
}

function AgentsPage() {
  return <><PageHero eyebrow="AI agents" title="Specialist agents. Connected to real work." text="Choose the job you need done. We build the agent, integrate your tools, and design the guardrails that make it useful in production."/><section className="px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><AgentCards/></div></section><ContactCTA/></>;
}

function SolutionsPage() {
  const solutions=[{icon:MessageSquare,title:'Customer experience',text:'Automate repetitive questions, triage requests, and route complex cases with context.'},{icon:Zap,title:'Sales & lead operations',text:'Qualify inbound leads, research prospects, prepare follow-ups, and update CRM records.'},{icon:Workflow,title:'Back-office workflows',text:'Move data between systems, summarize incoming work, and coordinate multi-step processes.'},{icon:Code2,title:'Internal knowledge',text:'Give employees a grounded assistant for company documents, procedures, and technical knowledge.'},{icon:Gauge,title:'Reporting & analysis',text:'Turn recurring reporting tasks into workflows that gather information and surface exceptions.'},{icon:Network,title:'Multi-agent systems',text:'Coordinate specialized agents with explicit roles, handoffs, and review steps.'}];
  return <><PageHero eyebrow="Solutions" title="Automate the busywork. Keep people in control." text="We map the friction in your business and connect AI to the workflow, data, and systems that already run it."/><section className="px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-4 sm:grid-cols-2 xl:grid-cols-3">{solutions.map(s=><article key={s.title} className="rounded-3xl border border-white/10 bg-white/[0.025] p-7"><s.icon className="text-lime-200" size={24}/><h2 className="mt-5 text-xl font-bold text-white">{s.title}</h2><p className="mt-3 text-sm leading-7 text-slate-400">{s.text}</p></article>)}</div></section><ContactCTA/></>;
}

function ProcessPage() {
  return <><PageHero eyebrow="Our process" title="A clear path from idea to working AI." text="We start with a real workflow, test the system against realistic cases, and plan for monitoring and ownership before launch."/><section className="px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><ProcessSection/><div className="mt-8 grid gap-4 md:grid-cols-3">{[{title:'Evaluation first',text:'Define what a correct result looks like and test it before release.'},{title:'Integrations included',text:'Connect the tools, data sources, and handoffs the workflow depends on.'},{title:'Visible operations',text:'Track behavior, exceptions, latency, and usage so issues can be acted on.'}].map(x=><div key={x.title} className="rounded-2xl border border-white/10 p-5"><h3 className="font-bold text-white">{x.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{x.text}</p></div>)}</div></div></section><ContactCTA/></>;
}

function PricingPage() {
  const plans=[{name:'Starter Agent',desc:'For one focused, well-defined workflow.',price:'Let’s scope it',features:['One primary agent workflow','Core system integrations','Basic evaluation and guardrails','Launch guidance']},{name:'Business Automation',desc:'For teams connecting several tools and tasks.',price:'Custom scope',features:['Multi-step workflows','CRM or helpdesk integrations','Monitoring and exception handling','Evaluation suite and handover']},{name:'AI Systems',desc:'For advanced knowledge or multi-agent systems.',price:'Custom scope',features:['RAG or multi-agent architecture','Multiple data sources and tools','Detailed evaluation and observability','Deployment and ownership planning']}];
  return <><PageHero eyebrow="Pricing" title="The right scope for the work." text="AI project costs depend on integrations, data readiness, risk, and workflow complexity. Start with the job to be done and we’ll help define a sensible scope."/><section className="px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-4 lg:grid-cols-3">{plans.map((p,i)=><article key={p.name} className={`rounded-3xl border p-7 ${i===1?'border-lime-300/40 bg-lime-300/[0.055]':'border-white/10 bg-white/[0.025]'}`}><span className="text-xs font-bold uppercase tracking-[.16em] text-lime-200">{p.name}</span><p className="mt-4 text-sm leading-6 text-slate-400">{p.desc}</p><h2 className="mt-6 text-2xl font-extrabold text-white">{p.price}</h2><a href="/contact" className="mt-6 flex items-center justify-center gap-2 rounded-full bg-lime-300 px-4 py-3 text-sm font-bold text-slate-950 transition hover:bg-lime-200">Discuss this scope <ArrowUpRight size={16}/></a><div className="mt-7 space-y-3">{p.features.map(f=><div key={f} className="flex gap-2.5 text-sm text-slate-300"><Check size={16} className="mt-0.5 shrink-0 text-lime-200"/>{f}</div>)}</div></article>)}</div><p className="mx-auto mt-6 max-w-7xl text-xs leading-6 text-slate-500">Plans above are scoping guides, not a binding quote. Final pricing is confirmed after reviewing your workflow and integration requirements.</p></section><ContactCTA/></>;
}

function AboutPage() {
  return <><PageHero eyebrow="About Orken AI" title="We build AI software that does the work, not just describes it." text="Orken AI focuses on practical agents and automations: systems that connect to your tools, work within clear guardrails, and are evaluated against the outcomes they are meant to improve."/><section className="px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-3">{[{icon:Zap,title:'Ship useful systems',text:'Focus on a real task and deliver a working system rather than a slide deck.'},{icon:ShieldCheck,title:'Measure and observe',text:'Build evaluation, logging, and fallback behavior into the delivery plan.'},{icon:Layers3,title:'Keep ownership clear',text:'Use understandable tools and documented integrations that teams can maintain.'}].map(x=><article key={x.title} className="rounded-3xl border border-white/10 bg-white/[0.025] p-7"><x.icon size={24} className="text-lime-200"/><h2 className="mt-5 text-xl font-bold text-white">{x.title}</h2><p className="mt-3 text-sm leading-7 text-slate-400">{x.text}</p></article>)}</div><div className="mx-auto mt-8 max-w-7xl rounded-3xl border border-white/10 bg-[#0d121d] p-7 sm:p-10"><h2 className="text-2xl font-extrabold text-white">The stack is a means, not the product.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-400">We work with language models, workflow tools, retrieval systems, voice infrastructure, and business applications. The right combination depends on your data, security needs, expected traffic, and what success means to your team.</p><div className="mt-6 flex flex-wrap gap-2">{tech.map(t=><span key={t} className="rounded-full border border-white/10 px-3 py-2 text-xs text-slate-300">{t}</span>)}</div></div></section><ContactCTA/></>;
}

function ContactPage() {
  return <><PageHero eyebrow="Contact" title="Let’s find the right workflow to automate." text="Tell us what your team does manually today, what tools you use, and what you would like to improve. We’ll use that context to shape the next step."/><section className="px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><h2 className="text-2xl font-bold text-white">Start with the problem.</h2><p className="mt-4 text-sm leading-7 text-slate-400">A useful first conversation covers the task, current process, systems involved, and the result you want. You don’t need a fully formed AI specification.</p><div className="mt-7 space-y-4">{['Which task is repetitive or slow?','What software or data does it use?','What should improve: speed, quality, cost, or coverage?'].map(x=><div key={x} className="flex gap-3 text-sm text-slate-300"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-lime-300/10 text-lime-200"><Check size={14}/></span>{x}</div>)}</div></div><div className="rounded-3xl border border-white/10 bg-white/[0.025] p-7 sm:p-9"><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-white/10 p-5"><MessageSquare className="text-lime-200" size={22}/><h3 className="mt-4 font-bold text-white">Talk through your workflow</h3><p className="mt-2 text-sm leading-6 text-slate-400">Share the business problem and explore possible approaches.</p><a href="https://orken.us/" target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-lime-200">Visit Orken AI <ArrowUpRight size={15}/></a></div><div className="rounded-2xl border border-white/10 p-5"><Cpu className="text-lime-200" size={22}/><h3 className="mt-4 font-bold text-white">Explore agent capabilities</h3><p className="mt-2 text-sm leading-6 text-slate-400">Compare voice, support, sales, knowledge, and workflow automation.</p><a href="/ai-agents" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-lime-200">View AI agents <ArrowRight size={15}/></a></div></div><p className="mt-5 text-xs leading-6 text-slate-500">This contact page is ready for your preferred form provider or CRM connection. No enquiry is stored or sent until a backend is connected.</p></div></div></section><ContactCTA/></>;
}

function Footer() {
  return <footer className="border-t border-white/[0.08] bg-[#07090f] px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-[1.5fr_1fr_1fr_1fr]"><div><a href="/" className="inline-flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-lime-300 text-slate-950"><Sparkles size={19}/></span><span className="text-lg font-extrabold text-white">orken<span className="text-lime-300">.ai</span></span></a><p className="mt-4 max-w-xs text-sm leading-6 text-slate-500">Production-minded AI agents and workflow automation for the work your business needs done.</p></div><div><h3 className="text-xs font-bold uppercase tracking-[.16em] text-slate-300">Explore</h3><div className="mt-4 space-y-3">{navItems.slice(1,4).map(n=><a key={n.page} href={n.href} className="block text-sm text-slate-500 hover:text-white">{n.label}</a>)}</div></div><div><h3 className="text-xs font-bold uppercase tracking-[.16em] text-slate-300">Solutions</h3><div className="mt-4 space-y-3"><a href="/solutions" className="block text-sm text-slate-500 hover:text-white">Business automation</a><a href="/ai-agents" className="block text-sm text-slate-500 hover:text-white">AI agent development</a><a href="/pricing" className="block text-sm text-slate-500 hover:text-white">Pricing & scope</a></div></div><div><h3 className="text-xs font-bold uppercase tracking-[.16em] text-slate-300">Get started</h3><p className="mt-4 text-sm leading-6 text-slate-500">Have a workflow in mind? Start by defining the task and desired outcome.</p><a href="/contact" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-lime-200">Contact Orken AI <ArrowRight size={15}/></a></div></div><div className="mt-10 flex flex-col gap-3 border-t border-white/[0.08] pt-6 text-xs text-slate-600 sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} Orken AI. All rights reserved.</span><span>Built for real workflows. Designed for clarity.</span></div></div></footer>;
}

export default function OrkenSite() {
  const path = window.location.pathname.replace(/\/+$/, '') || '/';
  const page: Page = path === '/ai-agents' ? 'agents' : path === '/solutions' ? 'solutions' : path === '/process' ? 'process' : path === '/pricing' ? 'pricing' : path === '/about' ? 'about' : path === '/contact' ? 'contact' : 'home';
  const titles: Record<Page, string> = { home: 'Orken AI | Production AI Agents & Workflow Automation', agents: 'AI Agents | Orken AI', solutions: 'AI Automation Solutions | Orken AI', process: 'Our Process | Orken AI', pricing: 'Pricing & Scope | Orken AI', about: 'About Orken AI', contact: 'Contact Orken AI' };
  document.title = titles[page];
  const descriptions: Record<Page, string> = { home: 'Build production AI agents and end-to-end workflow automation for sales, support, and operations.', agents: 'Explore voice agents, customer support bots, sales SDR agents, custom copilots, RAG, and workflow automation.', solutions: 'Practical AI automation for customer experience, sales, operations, knowledge, reporting, and multi-agent systems.', process: 'Discover how Orken AI scopes, builds, evaluates, launches, and improves production AI agents.', pricing: 'AI automation project scoping for focused agents, business workflows, and advanced AI systems.', about: 'Orken AI builds useful, observable, production-minded AI agents and workflow automation.', contact: 'Discuss your business workflow and explore the right AI automation approach with Orken AI.' };
  const meta = document.querySelector('meta[name="description"]');
  if (meta) meta.setAttribute('content', descriptions[page]);
  return <div className="min-h-screen bg-[#080b12] text-white selection:bg-lime-300 selection:text-slate-950"><Header page={page}/><main>{page === 'home' ? <HomePage/> : page === 'agents' ? <AgentsPage/> : page === 'solutions' ? <SolutionsPage/> : page === 'process' ? <ProcessPage/> : page === 'pricing' ? <PricingPage/> : page === 'about' ? <AboutPage/> : <ContactPage/>}</main><Footer/></div>;
}
